spring.application.name=kira-ai-backend
server.port=8080
spring.data.mongodb.uri=${MONGODB_URI}
app.google.client-id=${GOOGLE_CLIENT_ID}
app.gemini.api-key=${GEMINI_API_KEY}


logging.level.org.springframework.security=DEBUG
logging.level.com.kiraai.backend=DEBUG